print ("This is our madlib!! Have fun! -dhamar and caitrin")

difficulty = input("Press 1 to play on easy. Press 2 to play on medium. Press 3 to play on hard.")

if difficulty == ("1"):
	print ("You chose easy")
	Adjective1 = input ("Pick an adjective")
	Name1 = input ("Pick a person's name")
	Name2 = input ("Pick another person's name")
	Noun1 = input ("Pick any noun")
	Noun2 = input ("Pick another noun")
	print ("One " + Adjective1 + " day, " + Name1 + " and " + Name2 + " went to the beach! They decided to take " + Noun1 + " and " + Noun2 + " with them because " + Name1 + " wanted to " + Verb1 + " the " + Noun2 + ".")
elif difficulty == ("2"):
	print ("You chose medium")
	Adjective1 = input ("Pick an adjective")
	Name1 = input ("Pick a person's name")
	Name2 = input ("Pick another person's name")
	Noun1 = input ("Pick any noun")
	Noun2 = input ("Pick another noun")
	Name3 = input ("Pick another name")
	Verb1 = input ("Pick a verb")
	Exclamation = input ("Pick an exclamation")
	print ("One " + Adjective1 + " day, " + Name1 + " and " + Name2 + " went to the beach! They decided to take " + Noun1 + " and " + Noun2 + " with them because " + Name1 + " wanted to " + Verb1 + " the " + Noun2 + ". As they reached the water," + Name3 + "shouted '" + Exclamation + ", you guys!'")
elif difficulty == ("3"):
	print ("You chose hard")
	Adjective1 = input ("Pick an adjective")
	Name1 = input ("Pick a person's name")
	Name2 = input ("Pick another person's name")
	Noun1 = input ("Pick any noun")
	Noun2 = input ("Pick another noun")
	Name3 = input ("Pick another name")
	Verb1 = input ("Pick a verb")
	Exclamation = input ("Pick an exclamation")
	Verb2 = input ("Pick another verb")
	Adjective2 = input ("Pick another adjective")
	Emotion = input ("Pick an emotion")
	Verb3 = input ("Pick another verb")
	print ("One " + Adjective1 + " day, " + Name1 + " and " + Name2 + " went to the beach! They decided to take " + Noun1 + " and " + Noun2 + " with them because " + Name1 + " wanted to " + Verb1 + " the " + Noun2 + ". As they reached the water," + Name3 + "shouted '" + Exclamation + ", you guys!'" + Name1 + " and " + Name2 + " started " + Verb2 + "ing because they were " + Adjective2 + "ed to see " + Name3 + ". " + Name3 + " felt " + Emotion + " after " + Name1 + " and " + Name2 + Verb3 + "ed." + Noun2 + " came to life and attacked them all!") 
else:
	print ("Please pick a difficulty.")
